import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const questions = [
  {
    category: "Sport",
    question: "Koliko igrača ima nogometna momčad na terenu?",
    optionA: "9",
    optionB: "10",
    optionC: "11",
    optionD: "12",
    correctAnswer: "11",
  },
  {
    category: "Sport",
    question: "Koji sport igra Novak Đoković?",
    optionA: "Nogomet",
    optionB: "Košarka",
    optionC: "Tenis",
    optionD: "Rukomet",
    correctAnswer: "Tenis",
  },
  {
    category: "Sport",
    question: "Koliko traje nogometna utakmica?",
    optionA: "80 min",
    optionB: "90 min",
    optionC: "100 min",
    optionD: "120 min",
    correctAnswer: "90 min",
  },
  {
    category: "Sport",
    question: "Koliko igrača ima košarkaška ekipa na terenu?",
    optionA: "4",
    optionB: "5",
    optionC: "6",
    optionD: "7",
    correctAnswer: "5",
  },
  {
    category: "Sport",
    question: "Koji se Grand Slam igra u Londonu?",
    optionA: "US Open",
    optionB: "Australian Open",
    optionC: "Wimbledon",
    optionD: "Roland Garros",
    correctAnswer: "Wimbledon",
  },

  {
    category: "Geografija",
    question: "Koji je glavni grad Hrvatske?",
    optionA: "Split",
    optionB: "Rijeka",
    optionC: "Zagreb",
    optionD: "Osijek",
    correctAnswer: "Zagreb",
  },
  {
    category: "Geografija",
    question: "Koja je najveća država na svijetu?",
    optionA: "SAD",
    optionB: "Kina",
    optionC: "Kanada",
    optionD: "Rusija",
    correctAnswer: "Rusija",
  },
  {
    category: "Geografija",
    question: "Koja rijeka prolazi kroz Budimpeštu?",
    optionA: "Dunav",
    optionB: "Sava",
    optionC: "Drava",
    optionD: "Rajna",
    correctAnswer: "Dunav",
  },
  {
    category: "Geografija",
    question: "Na kojem kontinentu se nalazi Egipat?",
    optionA: "Azija",
    optionB: "Afrika",
    optionC: "Europa",
    optionD: "Australija",
    correctAnswer: "Afrika",
  },
  {
    category: "Geografija",
    question: "Koji je glavni grad Italije?",
    optionA: "Milano",
    optionB: "Napulj",
    optionC: "Rim",
    optionD: "Torino",
    correctAnswer: "Rim",
  },

  {
    category: "Matematika",
    question: "Koliko je 8 × 7?",
    optionA: "54",
    optionB: "56",
    optionC: "58",
    optionD: "64",
    correctAnswer: "56",
  },
  {
    category: "Matematika",
    question: "Koliko je kvadratni korijen od 81?",
    optionA: "7",
    optionB: "8",
    optionC: "9",
    optionD: "10",
    correctAnswer: "9",
  },
  {
    category: "Matematika",
    question: "Koliko je 15 + 27?",
    optionA: "42",
    optionB: "43",
    optionC: "44",
    optionD: "45",
    correctAnswer: "42",
  },
  {
    category: "Matematika",
    question: "Koliko stupnjeva ima pravi kut?",
    optionA: "45",
    optionB: "90",
    optionC: "180",
    optionD: "360",
    correctAnswer: "90",
  },
  {
    category: "Matematika",
    question: "Koliko je 12²?",
    optionA: "124",
    optionB: "132",
    optionC: "144",
    optionD: "156",
    correctAnswer: "144",
  },

  {
    category: "Računarstvo",
    question: "Što znači CPU?",
    optionA: "Central Processing Unit",
    optionB: "Computer Power Unit",
    optionC: "Central Program Utility",
    optionD: "Core Power Unit",
    correctAnswer: "Central Processing Unit",
  },
  {
    category: "Računarstvo",
    question: "Koji je programski jezik razvijen od Microsofta?",
    optionA: "Java",
    optionB: "Python",
    optionC: "C#",
    optionD: "PHP",
    correctAnswer: "C#",
  },
  {
    category: "Računarstvo",
    question: "Što znači HTML?",
    optionA: "Hyper Text Markup Language",
    optionB: "High Text Machine Language",
    optionC: "Home Tool Markup Language",
    optionD: "Hyper Tool Machine Language",
    correctAnswer: "Hyper Text Markup Language",
  },
  {
    category: "Računarstvo",
    question: "Koja tvrtka razvija Windows?",
    optionA: "Apple",
    optionB: "Google",
    optionC: "Microsoft",
    optionD: "IBM",
    correctAnswer: "Microsoft",
  },
  {
    category: "Računarstvo",
    question: "Koja je ekstenzija TypeScript datoteka?",
    optionA: ".js",
    optionB: ".tsx",
    optionC: ".ts",
    optionD: ".jsx",
    correctAnswer: ".ts",
  },

  {
    category: "Povijest",
    question: "Koje godine je završio Drugi svjetski rat?",
    optionA: "1943",
    optionB: "1944",
    optionC: "1945",
    optionD: "1946",
    correctAnswer: "1945",
  },
  {
    category: "Povijest",
    question: "Tko je bio prvi predsjednik SAD-a?",
    optionA: "Abraham Lincoln",
    optionB: "George Washington",
    optionC: "John Adams",
    optionD: "Thomas Jefferson",
    correctAnswer: "George Washington",
  },
  {
    category: "Povijest",
    question: "U kojem gradu se nalazi Koloseum?",
    optionA: "Atena",
    optionB: "Rim",
    optionC: "Pariz",
    optionD: "Madrid",
    correctAnswer: "Rim",
  },
  {
    category: "Povijest",
    question: "Tko je otkrio Ameriku 1492. godine?",
    optionA: "Marco Polo",
    optionB: "Kristofor Kolumbo",
    optionC: "Magellan",
    optionD: "Vasco da Gama",
    correctAnswer: "Kristofor Kolumbo",
  },
  {
    category: "Povijest",
    question: "Koje je carstvo izgradilo Machu Picchu?",
    optionA: "Rimsko",
    optionB: "Egipatsko",
    optionC: "Inke",
    optionD: "Maje",
    correctAnswer: "Inke",
  },

  {
    category: "Znanost",
    question: "Koji je kemijski simbol za vodu?",
    optionA: "O2",
    optionB: "CO2",
    optionC: "H2O",
    optionD: "HO",
    correctAnswer: "H2O",
  },
  {
    category: "Znanost",
    question: "Koliko planeta ima Sunčev sustav?",
    optionA: "7",
    optionB: "8",
    optionC: "9",
    optionD: "10",
    correctAnswer: "8",
  },
  {
    category: "Znanost",
    question: "Koji je najbliži planet Suncu?",
    optionA: "Venera",
    optionB: "Mars",
    optionC: "Merkur",
    optionD: "Zemlja",
    correctAnswer: "Merkur",
  },
  {
    category: "Znanost",
    question: "Koji organ pumpa krv kroz tijelo?",
    optionA: "Mozak",
    optionB: "Pluća",
    optionC: "Srce",
    optionD: "Jetra",
    correctAnswer: "Srce",
  },
  {
    category: "Znanost",
    question: "Koji plin biljke koriste u fotosintezi?",
    optionA: "Kisik",
    optionB: "Dušik",
    optionC: "Ugljikov dioksid",
    optionD: "Helij",
    correctAnswer: "Ugljikov dioksid",
  },
];

async function main() {
  await prisma.question.createMany({
    data: questions,
    skipDuplicates: true,
  });

  console.log("Pitanja su uspješno dodana.");
}

main()
  .catch((error) => {
    console.error(error);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });